{
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "runs": [
    {
      "results": [
        {
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "src/main.py",
                  "uriBaseId": "%SRCROOT%"
                },
                "region": {
                  "endLine": 142,
                  "startLine": 142
                }
              }
            }
          ],
          "message": {
            "markdown": "Internal Server Error in 'GET /exception'.\n\n# Sample Request\n\n```http\nGET /exception HTTP/1.1\nx-mapi-program-uuid: 387c63c0-7f07-4f60-a709-bf2ca1353aff\n\n```\n\n# Sample Response\n\n```http\nHTTP/1.1 500 Internal Server Error\ndate: Thu, 27 May 2021 18:09:34 GMT\nserver: uvicorn\ncontent-length: 1549\n\nTraceback (most recent call last):\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/starlette/middleware/errors.py\", line 159, in __call__\n    await self.app(scope, receive, _send)\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/starlette/exceptions.py\", line 82, in __call__\n    raise exc from None\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/starlette/exceptions.py\", line 71, in __call__\n    await self.app(scope, receive, sender)\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/starlette/routing.py\", line 580, in __call__\n    await route.handle(scope, receive, send)\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/starlette/routing.py\", line 241, in handle\n    await self.app(scope, receive, send)\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/starlette/routing.py\", line 52, in app\n    response = await func(request)\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/fastapi/routing.py\", line 201, in app\n    raw_response = await run_endpoint_function(\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/fastapi/routing.py\", line 148, in run_endpoint_function\n    return await dependant.call(**values)\n  File \"/Users/apr/fas/gh/code-scanning-experiments/./src/main.py\", line 138, in exception\n    inner()\n  File \"/Users/apr/fas/gh/code-scanning-experiments/./src/main.py\", line 142, in inner\n    s = json.loads(open(\"/tmp/out\").read())\nNameError: name 'json' is not defined\n\n```\n\n[Details](https://mayhem4api.forallsecure.com/issues/3169/23503)\n",
            "text": "Internal Server Error in 'GET /exception'. [Details](https://mayhem4api.forallsecure.com/issues/3169/23503)"
          },
          "ruleId": "internal-server-error"
        },
        {
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "src/main.py",
                  "uriBaseId": "%SRCROOT%"
                },
                "region": {
                  "endLine": 142,
                  "startLine": 142
                }
              }
            }
          ],
          "message": {
            "markdown": "Internal Server Error in 'GET /exception'.\n\n# Sample Request\n\n```http\nGET /exception HTTP/1.1\nx-mapi-program-uuid: 0c92ae7b-4d1c-4870-8913-480118de3c4c\n\n```\n\n# Sample Response\n\n```http\nHTTP/1.1 500 Internal Server Error\ndate: Thu, 27 May 2021 18:09:39 GMT\nserver: uvicorn\ncontent-length: 1549\n\nTraceback (most recent call last):\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/starlette/middleware/errors.py\", line 159, in __call__\n    await self.app(scope, receive, _send)\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/starlette/exceptions.py\", line 82, in __call__\n    raise exc from None\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/starlette/exceptions.py\", line 71, in __call__\n    await self.app(scope, receive, sender)\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/starlette/routing.py\", line 580, in __call__\n    await route.handle(scope, receive, send)\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/starlette/routing.py\", line 241, in handle\n    await self.app(scope, receive, send)\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/starlette/routing.py\", line 52, in app\n    response = await func(request)\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/fastapi/routing.py\", line 201, in app\n    raw_response = await run_endpoint_function(\n  File \"/Users/apr/.pyenv/versions/3.9.5/lib/python3.9/site-packages/fastapi/routing.py\", line 148, in run_endpoint_function\n    return await dependant.call(**values)\n  File \"/Users/apr/fas/gh/code-scanning-experiments/./src/main.py\", line 138, in exception\n    inner()\n  File \"/Users/apr/fas/gh/code-scanning-experiments/./src/main.py\", line 142, in inner\n    s = json.loads(open(\"/tmp/out\").read())\nNameError: name 'json' is not defined\n\n```\n\n[Details](https://mayhem4api.forallsecure.com/issues/3169/23504)\n",
            "text": "Internal Server Error in 'GET /exception'. [Details](https://mayhem4api.forallsecure.com/issues/3169/23504)"
          },
          "ruleId": "internal-server-error"
        },
        {
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "unknown-file",
                  "uriBaseId": "%SRCROOT%"
                },
                "region": {
                  "endLine": 1,
                  "startLine": 1
                }
              }
            }
          ],
          "message": {
            "markdown": "Server Crash in 'GET /exception'.\n\n# Sample Request\n\n```http\nGET /exception HTTP/1.1\nx-mapi-program-uuid: e9d24b1c-d4dd-418c-ab2f-7d16d6c3431f\n\n```\n\n# Sample Response\n\n```http\nMissing response\n```\n\n[Details](https://mayhem4api.forallsecure.com/issues/3169/23505)\n",
            "text": "Server Crash in 'GET /exception'. [Details](https://mayhem4api.forallsecure.com/issues/3169/23505)"
          },
          "ruleId": "server-crash"
        }
      ],
      "tool": {
        "driver": {
          "fullName": "Mayhem for API",
          "name": "mAPI",
          "rules": [
            {
              "defaultConfiguration": {
                "level": "error"
              },
              "fullDescription": {
                "text": "The API returned an Internal Server Error, indicating an unhandled exception."
              },
              "help": {
                "text": "Consider adding consistent error handling mechanisms which are capable of\nhandling any user input to your API. Ideally, the error would return a 4xx\nstatus like '400 Bad Request', and provide meaningful details to end-users so\nthey understand how to fix their request.\n\nAlso, ensure that in production those error messages are not providing\ninformation useful to an attacker, like a stacktrace.\n"
              },
              "id": "internal-server-error",
              "properties": {
                "tags": [
                  "CWE-20",
                  "CWE-391",
                  "CWE-550"
                ]
              },
              "shortDescription": {
                "text": "Internal Server Error"
              }
            },
            {
              "defaultConfiguration": {
                "level": "warning"
              },
              "fullDescription": {
                "text": "A server that can be forced to crash may be vulnerable to denial-of-service attacks."
              },
              "help": {
                "text": "Ensure that unhandled errors cannot take down the entire server and does not\nimpact subsequent requests.\n"
              },
              "id": "server-crash",
              "properties": {
                "tags": [
                  "CWE-730"
                ]
              },
              "shortDescription": {
                "text": "Server Crash"
              }
            }
          ],
          "semanticVersion": "2.6.6"
        }
      }
    }
  ],
  "version": "2.1.0"
}